/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface FloDatetime {
    'displayFormat': string;
    'max': string;
    'min': string;
    'text': string;
    'value': string;
  }
}

declare global {


  interface HTMLFloDatetimeElement extends Components.FloDatetime, HTMLStencilElement {}
  var HTMLFloDatetimeElement: {
    prototype: HTMLFloDatetimeElement;
    new (): HTMLFloDatetimeElement;
  };
  interface HTMLElementTagNameMap {
    'flo-datetime': HTMLFloDatetimeElement;
  }
}

declare namespace LocalJSX {
  interface FloDatetime {
    'displayFormat'?: string;
    'max'?: string;
    'min'?: string;
    'text'?: string;
    'value'?: string;
  }

  interface IntrinsicElements {
    'flo-datetime': FloDatetime;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'flo-datetime': LocalJSX.FloDatetime & JSXBase.HTMLAttributes<HTMLFloDatetimeElement>;
    }
  }
}


